const heroImages = [
    'FLOATING WEB/floating_1.webp',
    'FLOATING WEB/floating_2.webp',
    'FLOATING WEB/floating_3.webp',
    'FLOATING WEB/floating_4.webp',
    'FLOATING WEB/floating_5.webp',
    'FLOATING WEB/floating_6.webp',
    'FLOATING WEB/floating_7.webp',
    'FLOATING WEB/floating_8.webp',
    'FLOATING WEB/floating_9.webp',
    'FLOATING WEB/floating_10.webp',
    'FLOATING WEB/floating_11.webp',
    'FLOATING WEB/floating_12.webp',
    'FLOATING WEB/floating_13.webp',
    'FLOATING WEB/floating_14.webp',
];
